/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistDescriptionRouteImport } from './routes/api/assist-description'
import { Route as ApiDetectSiteRouteImport } from './routes/api/detect-site'
import { Route as ApiGenerateProposalRouteImport } from './routes/api/generate-proposal'
import { Route as ApiRegenerateSectionRouteImport } from './routes/api/regenerate-section'
import { Route as ApiSummariseProposalRouteImport } from './routes/api/summarise-proposal'
import { Route as ProposalIdRouteImport } from './routes/proposal.$id'
import { Route as ShareTokenRouteImport } from './routes/share.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistDescriptionRoute = ApiAssistDescriptionRouteImport.update({
  id: '/api/assist-description',
  path: '/api/assist-description',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDetectSiteRoute = ApiDetectSiteRouteImport.update({
  id: '/api/detect-site',
  path: '/api/detect-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateProposalRoute = ApiGenerateProposalRouteImport.update({
  id: '/api/generate-proposal',
  path: '/api/generate-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegenerateSectionRoute = ApiRegenerateSectionRouteImport.update({
  id: '/api/regenerate-section',
  path: '/api/regenerate-section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummariseProposalRoute = ApiSummariseProposalRouteImport.update({
  id: '/api/summarise-proposal',
  path: '/api/summarise-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIdRoute = ProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assist-description': typeof ApiAssistDescriptionRoute
  '/api/detect-site': typeof ApiDetectSiteRoute
  '/api/generate-proposal': typeof ApiGenerateProposalRoute
  '/api/regenerate-section': typeof ApiRegenerateSectionRoute
  '/api/summarise-proposal': typeof ApiSummariseProposalRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assist-description': typeof ApiAssistDescriptionRoute
  '/api/detect-site': typeof ApiDetectSiteRoute
  '/api/generate-proposal': typeof ApiGenerateProposalRoute
  '/api/regenerate-section': typeof ApiRegenerateSectionRoute
  '/api/summarise-proposal': typeof ApiSummariseProposalRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assist-description': typeof ApiAssistDescriptionRoute
  '/api/detect-site': typeof ApiDetectSiteRoute
  '/api/generate-proposal': typeof ApiGenerateProposalRoute
  '/api/regenerate-section': typeof ApiRegenerateSectionRoute
  '/api/summarise-proposal': typeof ApiSummariseProposalRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assist-description'
    | '/api/detect-site'
    | '/api/generate-proposal'
    | '/api/regenerate-section'
    | '/api/summarise-proposal'
    | '/proposal/$id'
    | '/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assist-description'
    | '/api/detect-site'
    | '/api/generate-proposal'
    | '/api/regenerate-section'
    | '/api/summarise-proposal'
    | '/proposal/$id'
    | '/share/$token'
  id:
    | '__root__'
    | '/'
    | '/api/assist-description'
    | '/api/detect-site'
    | '/api/generate-proposal'
    | '/api/regenerate-section'
    | '/api/summarise-proposal'
    | '/proposal/$id'
    | '/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssistDescriptionRoute: typeof ApiAssistDescriptionRoute
  ApiDetectSiteRoute: typeof ApiDetectSiteRoute
  ApiGenerateProposalRoute: typeof ApiGenerateProposalRoute
  ApiRegenerateSectionRoute: typeof ApiRegenerateSectionRoute
  ApiSummariseProposalRoute: typeof ApiSummariseProposalRoute
  ProposalIdRoute: typeof ProposalIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assist-description': {
      id: '/api/assist-description'
      path: '/api/assist-description'
      fullPath: '/api/assist-description'
      preLoaderRoute: typeof ApiAssistDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/detect-site': {
      id: '/api/detect-site'
      path: '/api/detect-site'
      fullPath: '/api/detect-site'
      preLoaderRoute: typeof ApiDetectSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-proposal': {
      id: '/api/generate-proposal'
      path: '/api/generate-proposal'
      fullPath: '/api/generate-proposal'
      preLoaderRoute: typeof ApiGenerateProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regenerate-section': {
      id: '/api/regenerate-section'
      path: '/api/regenerate-section'
      fullPath: '/api/regenerate-section'
      preLoaderRoute: typeof ApiRegenerateSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarise-proposal': {
      id: '/api/summarise-proposal'
      path: '/api/summarise-proposal'
      fullPath: '/api/summarise-proposal'
      preLoaderRoute: typeof ApiSummariseProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$id': {
      id: '/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssistDescriptionRoute: ApiAssistDescriptionRoute,
  ApiDetectSiteRoute: ApiDetectSiteRoute,
  ApiGenerateProposalRoute: ApiGenerateProposalRoute,
  ApiRegenerateSectionRoute: ApiRegenerateSectionRoute,
  ApiSummariseProposalRoute: ApiSummariseProposalRoute,
  ProposalIdRoute: ProposalIdRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
